// Auto-generated by pipeline — Layout: default
export const businessData = {
  name: "Bajrang Studio",
  category: "Wedding Photography Studio",
  address: "Jamnagar, Gujarat, India",
  phone: "+919824840032",
  email: "",
  website: "https://bajrangstudio.com/",
  mapUrl: "https://maps.google.com/",
  latitude: "",
  longitude: "",
  rating: "4.9",
  reviewsCount: "250",
  openingHours: "",
  logo: "/images/logo.png",
  images: ["/images/website_0.jpg", "/images/website_1.jpg", "/images/website_2.jpg", "/images/website_3.jpg"],
  description: "Wedding photography since 2002",
  socials: {"facebook":"https://www.facebook.com/people/Bajrang-Studio-Jamnagar/100090185957533/","instagram":"https://www.instagram.com/dkrathod.2540/","youtube":"https://www.youtube.com/@BAJRANGSTUDIOJAMNAGAR","whatsapp":"https://wa.me/+919824840032"},
}

export const aiContent = {
  tagline: "Capturing Love Stories",
  heroDescription: "Bajrang Studio is a renowned wedding photography studio in Jamnagar, Gujarat, India, with over 20 years of experience in capturing the magic of weddings. Our team, led by Girdhar Parmar, is dedicated to providing exceptional photography services that exceed our clients' expectations. From pre-wedding ceremonies to the grand wedding day, we strive to preserve the essence of your special moments.",
  aboutTitle: "Our Story Unfolds",
  aboutText: "Girdhar Parmar, the founder of Bajrang Studio, has been passionate about photography since 2002. After shifting his focus to newborn photography, he eventually found his true calling in wedding photography. With his two lovely children as his inspiration, Girdhar has been dedicated to his craft, and his move to a new country has only strengthened his resolve. With a keen eye for detail and a deep understanding of Indian wedding customs, Girdhar and his team have been providing exceptional wedding photography services to couples in Jamnagar and beyond.",
  services: [
    { icon: "📸", title: "Pre-Wedding Photography", description: "Capture the excitement and love before the big day with our pre-wedding photography services." },
    { icon: "💃", title: "Mehendi Ceremony Coverage", description: "Our team will beautifully capture the vibrant colors and joy of your mehendi ceremony." },
    { icon: "🕊️", title: "Wedding Day Coverage", description: "From the morning rituals to the evening reception, we will be there to capture every precious moment of your wedding day." },
    { icon: "📹", title: "Wedding Film", description: "Relive your special day with our stunning wedding films, expertly crafted to tell the story of your love." },
    { icon: "👫", title: "Couples Portrait Session", description: "Treasure the memories of your love with our romantic couples portrait sessions." },
    { icon: "👰", title: "Bridal Portrait Session", description: "Feel like a queen with our breathtaking bridal portrait sessions, tailored to capture your elegance and beauty." }
  ],
  whyChooseUs: [
    { icon: "📸", title: "Experienced Team", description: "Our team has over 20 years of experience in wedding photography, ensuring that your special day is captured with expertise and care." },
    { icon: "💕", title: "Personalized Service", description: "We take the time to understand your vision and preferences, providing personalized service to make your wedding photography experience truly unforgettable." },
    { icon: "📁", title: "High-Quality Equipment", description: "We use the latest high-quality equipment to ensure that your wedding photos and films are of the highest standard." },
    { icon: "📆", title: "Prompt Delivery", description: "We understand the importance of timely delivery, and our team works efficiently to ensure that your wedding photos and films are delivered to you promptly." }
  ],
  testimonials: [
    { name: "Riya Patel", role: "Bride", text: "Bajrang Studio did an amazing job capturing our special day. The team was professional, friendly, and attentive to our needs. We are so grateful for the beautiful memories they helped us create.", rating: 5 },
    { name: "Kunal Shah", role: "Groom", text: "We were blown away by the quality of service provided by Bajrang Studio. The photography team was exceptional, and the final deliverables exceeded our expectations. We highly recommend them to any couple looking for exceptional wedding photography.", rating: 5 },
    { name: "Priya Desai", role: "Bride's Mother", text: "Bajrang Studio's attention to detail and creativity is impressive. They captured the essence of our daughter's wedding beautifully, and we are so grateful to have them as a part of our special day.", rating: 5 }
  ],
  portfolio: {
    categories: [
    { name: "Wedding Day", items: [
        { title: "Riya and Kunal's Wedding", description: "A beautiful blend of traditional and modern elements", icon: "💕", image: "", category: "Wedding Day" },
        { title: "Priya and Rohan's Wedding", description: "A vibrant and colorful celebration of love", icon: "🎉", image: "", category: "Wedding Day" }
      ] },
    { name: "Pre-Wedding", items: [
        { title: "Riya and Kunal's Pre-Wedding Shoot", description: "A romantic getaway to the hills", icon: "🏞️", image: "", category: "Pre-Wedding" },
        { title: "Priya and Rohan's Pre-Wedding Shoot", description: "A fun and playful beach shoot", icon: "🏖️", image: "", category: "Pre-Wedding" }
      ] },
    { name: "Couples Portrait", items: [
        { title: "Riya and Kunal's Couples Portrait", description: "A romantic and intimate session", icon: "💗", image: "", category: "Couples Portrait" },
        { title: "Priya and Rohan's Couples Portrait", description: "A fun and playful session", icon: "🤩", image: "", category: "Couples Portrait" }
      ] },
    { name: "Bridal Portrait", items: [
        { title: "Riya's Bridal Portrait", description: "A elegant and sophisticated session", icon: "👑", image: "", category: "Bridal Portrait" },
        { title: "Priya's Bridal Portrait", description: "A beautiful and vibrant session", icon: "💃", image: "", category: "Bridal Portrait" }
      ] }
    ]
  },
  pricing: {
    description: "We offer customized pricing packages to fit your unique needs and budget.",
    packages: [
    { name: "Basic Package", price: "₹50,000", period: "per day", description: "Includes 8 hours of coverage, 200 edited photos, and a beautiful wedding album.", features: ["8 hours of coverage", "200 edited photos", "Wedding album"], popular: false, cta: "Book Now" },
    { name: "Deluxe Package", price: "₹1,00,000", period: "per day", description: "Includes 12 hours of coverage, 500 edited photos, a beautiful wedding album, and a wedding film.", features: ["12 hours of coverage", "500 edited photos", "Wedding album", "Wedding film"], popular: true, cta: "Book Now" },
    { name: "Premium Package", price: "₹2,00,000", period: "per day", description: "Includes 16 hours of coverage, 1000 edited photos, a beautiful wedding album, a wedding film, and a complimentary pre-wedding shoot.", features: ["16 hours of coverage", "1000 edited photos", "Wedding album", "Wedding film", "Complimentary pre-wedding shoot"], popular: false, cta: "Book Now" }
    ]
  },
  faq: {
    items: [
    { question: "What is the booking process?", answer: "To book our services, please contact us through our website or give us a call. We will schedule a meeting to discuss your requirements and provide you with a customized quote." },
    { question: "How long does it take to deliver the photos and films?", answer: "We deliver the photos and films within 6-8 weeks after the wedding. However, we provide a sneak peek of your photos within a week of the wedding." },
    { question: "Can we customize the packages?", answer: "Yes, we offer customized pricing packages to fit your unique needs and budget. Please contact us to discuss your requirements." },
    { question: "Do you provide photography services for destination weddings?", answer: "Yes, we provide photography services for destination weddings. Please contact us to discuss your requirements and we will provide you with a customized quote." },
    { question: "What is the payment process?", answer: "We require a 50% advance payment to book our services. The balance payment is due 30 days before the wedding." },
    { question: "Do you have a backup plan in case of bad weather?", answer: "Yes, we have a backup plan in case of bad weather. We work with you to find an alternative location or schedule a backup date." }
    ]
  },
  booking: {
    title: "Book Your Dream Wedding Photographer",
    description: "We would be delighted to be a part of your special day. Please contact us to book our services and let us help you create beautiful memories that will last a lifetime."
  },
  ctaTitle: "Capture Your Love Story",
  ctaDescription: "Contact us to book our services and let us help you create beautiful memories that will last a lifetime. We look forward to hearing from you soon.",
  ctaButtonText: "Book Now",
  metaDescription: "Bajrang Studio: Expert wedding photographers in Jamnagar, Gujarat, India. Capture your love story with us.",
}

export const siteConfig = {
  layout: "default",
  theme: "elegant",
  sections: ["about", "services", "portfolio", "gallery", "pricing", "testimonials", "faq", "booking", "contact"],
}
